services:
#  postgres:
#    image: postgres:13
#    container_name: postgres
#    environment:
#      POSTGRES_USER: postgres
#      POSTGRES_PASSWORD: postgres
#      POSTGRES_DB: postgres
#    ports:
#      - "5432:5432"
#    volumes:
#      - pg_data:/var/lib/postgresql/data

  keycloak:
    image: quay.io/keycloak/keycloak:26.1.2
    container_name: keycloak
    ports:
      - "8080:8080"
    environment:
      - KC_BOOTSTRAP_ADMIN_USERNAME=admin
      - KC_BOOTSTRAP_ADMIN_PASSWORD=admin
      - KC_DB=dev-file
      - KC_CACHE=local
    command:
      - start-dev
    volumes:
      - ./data/keycloak:/opt/keycloak/data

  eureka-server:
    build: eureka-server/eureka-server
    mem_limit: 512m
    container_name: eureka-server
    ports:
      - "8761:8761"
#
  config-server:
    build: config-server/
    mem_limit: 512m
    container_name: config-server
    ports:
      - "8888:8888"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8888/actuator/health"]
      interval: 30s
      timeout: 10s
      retries: 3
    depends_on:
      - eureka-server
#
  api-gateway:
    build: api-gateway/api-gateway
    mem_limit: 512m
    container_name: api-gateway
    ports:
      - "8081:8081"
    depends_on:
       config-server:
            condition: service_healthy
#
  login-service:
    build: login-service/login-service/
    mem_limit: 512m
    container_name: login-service
    ports:
      - "8083:8083"
    depends_on:
      - api-gateway

  account-service:
    build: account-service/account-service/
    mem_limit: 512m
    container_name: account-service
    ports:
      - "8084:8084"
    depends_on:
      - api-gateway

#
#  activities-service:
#    build: Activities-Service/activities-service/
#    mem_limit: 512m
#    ports:
#      - "8087:8080"
#    depends_on:
#      - api-gateway
#
#  card-service:
#    build: Cards-service/cards-service/
#    mem_limit: 512m
#    ports:
#      - "8085:8080"
#    depends_on:
#      - api-gateway
#
  user-service:
    build: user-service/user-service/
    mem_limit: 512m
    container_name: user-service
    ports:
      - "8086:8086"
    depends_on:
      - api-gateway

#volumes:
#  pg_data:



