services:
  db:
    image: postgres:13
    container_name: db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres1234
      POSTGRES_DB: digitalbank
    ports:
      - "5432:5432"
    volumes:
      - ./data_db:/var/lib/postgresql/data

  keycloak:
    image: quay.io/keycloak/keycloak:26.1.2
    container_name: keycloak
    ports:
      - "8080:8080"
    environment:
      - KC_BOOTSTRAP_ADMIN_USERNAME=admin
      - KC_BOOTSTRAP_ADMIN_PASSWORD=admin
      - KC_DB=dev-file
      - KC_CACHE=local
    command:
      - start-dev
    volumes:
      - ./data/keycloak:/opt/keycloak/data
#
  eureka-server:
    build: eureka-server/eureka-server
    mem_limit: 512m
    container_name: eureka-server
    ports:
      - "8761:8761"
##
  config-server:
    build: config-server/
    mem_limit: 512m
    container_name: config-server
    ports:
      - "8888:8888"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8888/actuator/health"]
      interval: 30s
      timeout: 10s
      retries: 3
    depends_on:
      - eureka-server
##
  api-gateway:
    build: api-gateway/api-gateway
    mem_limit: 512m
    container_name: api-gateway
    ports:
      - "8081:8081"
    depends_on:
       config-server:
            condition: service_healthy
##
  login-service:
    build: login-service/login-service/
    mem_limit: 512m
    container_name: login-service
    ports:
      - "8083:8083"
    depends_on:
      - api-gateway
      - keycloak

  account-service:
    build: account-service/account-service/
    mem_limit: 512m
    container_name: account-service
    ports:
      - "8084:8084"
    depends_on:
      - api-gateway
      - db
#
##
  activities-service:
    build: Activities-Service/activities-service/
    mem_limit: 512m
    container_name: activites-service
    ports:
      - "8087:8087"
    depends_on:
      - api-gateway
      - db
##
  cards-service:
    build: Cards-service/cards-service/
    mem_limit: 512m
    container_name: cards-service
    ports:
      - "8085:8085"
    depends_on:
      - api-gateway
      - db
##
  user-service:
    build: user-service/user-service/
    mem_limit: 512m
    container_name: user-service
    ports:
      - "8086:8086"
    depends_on:
      - api-gateway

#volumes:
#  pg_data:



