server:
  port: 8081

spring:
  main:
    web-application-type: reactive

  cloud:
    gateway:
      default-filters:
        - TokenRelay
      routes:
        - id: login-service
          uri: lb://login-service
          predicates:
            - Path=/login/**
        - id: user-service
          uri: lb://user-service
          predicates:
            - Path=/users/**
          filters:
            - TokenRelay

  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://keycloak:8080/realms/backend-digital-money

eureka:
  client:
    service-url:
      defaultZone: http://eureka-server:8761/eureka/

management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: always
