server:
  port: 8081

spring:
  main:
    web-application-type: reactive

  cloud:
    gateway:
      default-filters:
        - TokenRelay
      routes:
        - id: login-service
          uri: lb://login-service
          predicates:
            - Path=/login/**
        - id: login-service
          uri: lb://login-service
          predicates:
             - Path=/register/**
        - id: user-service
          uri: lb://user-service
          predicates:
            - Path=/users/**
          filters:
            - TokenRelay
        - id: account-service
          uri: lb://account-service
          predicates:
            - Path=/accounts/**
          filters:
            - TokenRelay
            - StripPrefix=1
        - id: activities-service
          uri: lb://activities-service
          predicates:
            - Path=/activities/**
          filters:
            - TokenRelay
            - StripPrefix=1
        - id: cards-service
          uri: lb://cards-service
          predicates:
              - Path=/cards/**
          filters:
               - TokenRelay
               - StripPrefix=1

  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://keycloak:8080/realms/backend-digital-money

eureka:
  client:
    service-url:
      defaultZone: http://eureka-server:8761/eureka/,http://localhost:8761/eureka
  instance:
    prefer-ip-address: false
    hostname: localhost
    instance-id: ${spring.application.name}:${server.port}

management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: always
