urls:
  - name: activities-service
    url: /activities-service/v3/api-docs
  - name: cards-service
    url: /cards-service/v3/api-docs
  - name: user-service
    url: /user-service/v3/api-docs
  - name: account-service
    url: /account-service/v3/api-docs
  - name: login-service
    url: /login-service/v3/api-docs